# $schema: https://json.schemastore.org/spring-boot-application.json
server:
  port: 8082

spring:
  application:
    name: account

  datasource:
    url: jdbc:mysql://localhost:3306/accountdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: TestdbRoot
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    show-sql: true
    defer-datasource-initialization: false

    properties:
      hibernate:
        jdbc:
          batch_size: 50
          time_zone: Asia/Seoul
        order_inserts: true
        order_updates: true
        format_sql: true
        use_sql_comments: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: account-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.msa.event"
        spring.json.use.type.headers: true
