@baseUrl=http://localhost:8080/api

# User Account (401)
GET {{baseUrl}}/accounts/1

### regist async
POST {{baseUrl}}/users/async
Content-Type: application/json

{
  "email": "newer102@gmail.com",
  "name": "newer102",
  "passwd": "password123",
  "accountPasswd": "123456"
}

### login
POST {{baseUrl}}/users/login
Content-Type: application/x-www-form-urlencoded

username = 1@email.com &
password = pwd1

> {%
    client.global.set("auth_token", response.body.accessToken);
%}


### user info
GET {{baseUrl}}/users/1
Authorization: Bearer {{auth_token}}

### hello~
GET {{baseUrl}}/users/hello
Authorization: Bearer {{auth_token}}

### LoginUser Account
GET {{baseUrl}}/accounts/account-info
Authorization: Bearer {{auth_token}}

### LoginUser Stock info
GET {{baseUrl}}/stocks/stock-info
Authorization: Bearer {{auth_token}}

### deposit
PUT {{baseUrl}}/accounts?amount=2000
Authorization: Bearer {{auth_token}}


### withdrawal (body에 userid 제거!)
PATCH {{baseUrl}}/accounts
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "amount": 1000,
  "passwd": "123456"
}

### purchase stock
POST {{baseUrl}}/stocks/purchase
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "cnt": 2,
  "price": 1000.0,
  "accountPasswd": "123456"
}
