@baseUrl=http://localhost:8083/api/stocks

### purchase
PATCH {{baseUrl}}/1
Content-Type: application/json

{
  "userid": 2,
  "cnt": 2,
  "price": 1000.0,
  "accountPasswd": "123456"
}

### withdrawal
PATCH http://localhost:8082/internal/accounts/1
Content-Type: application/json

{
  "userid": 1,
  "amount": 1000,
  "passwd": "123456"
}
