@baseUrl=http://localhost:8081/api/users

### regist user
POST {{baseUrl}}
Content-Type: application/json

{
  "email": "newer2@gmail.com",
  "name": "newer2",
  "passwd": "password123",
  "accountPasswd": 123456
}

### regist user
POST {{baseUrl}}/async
Content-Type: application/json

{
  "email": "newer101@gmail.com",
  "name": "newer101",
  "passwd": "password123",
  "accountPasswd": 123456
}

### login
POST {{baseUrl}}/login
Content-Type: application/x-www-form-urlencoded

username = 1@email.com &
password = pwd1

> {%
    client.global.set("auth_token", response.body.accessToken);
%}


### user info
GET {{baseUrl}}/1
Authorization: Bearer {{auth_token}}

### hello~
GET {{baseUrl}}/hello
Authorization: Bearer {{auth_token}}


### kafka topics
GET http://localhost:8081/kafka/topics

### delete kafka topics
DELETE http://localhost:8081/kafka/topics?topics=user-regist
